name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: '~/Qt'
          version: '5.15.2'
      
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
